# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agregador.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agregador.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61gregador.proto\"!\n\x12\x41ggregationRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"\'\n\x13\x41ggregationResponse\x12\x10\n\x08resposta\x18\x01 \x01(\t2K\n\x0b\x41ggregation\x12<\n\x0fMakeAggregation\x12\x13.AggregationRequest\x1a\x14.AggregationResponseb\x06proto3'
)




_AGGREGATIONREQUEST = _descriptor.Descriptor(
  name='AggregationRequest',
  full_name='AggregationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='AggregationRequest.req', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=52,
)


_AGGREGATIONRESPONSE = _descriptor.Descriptor(
  name='AggregationResponse',
  full_name='AggregationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resposta', full_name='AggregationResponse.resposta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['AggregationRequest'] = _AGGREGATIONREQUEST
DESCRIPTOR.message_types_by_name['AggregationResponse'] = _AGGREGATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AggregationRequest = _reflection.GeneratedProtocolMessageType('AggregationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATIONREQUEST,
  '__module__' : 'agregador_pb2'
  # @@protoc_insertion_point(class_scope:AggregationRequest)
  })
_sym_db.RegisterMessage(AggregationRequest)

AggregationResponse = _reflection.GeneratedProtocolMessageType('AggregationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATIONRESPONSE,
  '__module__' : 'agregador_pb2'
  # @@protoc_insertion_point(class_scope:AggregationResponse)
  })
_sym_db.RegisterMessage(AggregationResponse)



_AGGREGATION = _descriptor.ServiceDescriptor(
  name='Aggregation',
  full_name='Aggregation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeAggregation',
    full_name='Aggregation.MakeAggregation',
    index=0,
    containing_service=None,
    input_type=_AGGREGATIONREQUEST,
    output_type=_AGGREGATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGGREGATION)

DESCRIPTOR.services_by_name['Aggregation'] = _AGGREGATION

# @@protoc_insertion_point(module_scope)
